# Generated by Django 3.1.14 on 2022-07-03 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20220416_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
