# Generated by Django 3.1.14 on 2022-10-03 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlisting',
            name='current_bid',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
