# Generated by Django 4.1.3 on 2022-11-28 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=64)),
            ],
        ),
        migrations.RemoveField(
            model_name='auctionlisting',
            name='category',
        ),
        migrations.AlterField(
            model_name='auctionlisting',
            name='current_bid',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='auctionlisting',
            name='img_link',
            field=models.URLField(max_length=1000),
        ),
    ]
