# Generated by Django 4.1.3 on 2022-12-13 14:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_remove_user_followers_following'),
    ]

    operations = [
        migrations.AddField(
            model_name='following',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='following_details', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
