# Generated by Django 4.1.3 on 2022-12-16 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_following_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='following',
            name='followers',
        ),
    ]
