# Generated by Django 4.1.3 on 2022-12-28 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0010_post_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
    ]
